services:
  # ğŸŒ Sistema principal
  - type: web
    name: tramite-web
    env: docker
    plan: free
    repo: https://github.com/dantejossue/sistema-de-tramite.git
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: tramite-db.onrender.com      # â¬…ï¸ cambio importante
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: sis_tramite
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: admin

  # ğŸŒ Base de datos, accesible externamente
  - type: web
    name: tramite-db
    env: docker
    plan: free
    repo: https://github.com/dantejossue/sistema-de-tramite.git
    dockerfilePath: ./mysql.Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: admin
      - key: MYSQL_DATABASE
        value: sis_tramite

  # ğŸŒ phpMyAdmin para pruebas
  - type: web
    name: phpmyadmin
    env: docker
    plan: free
    repo: https://github.com/dantejossue/sistema-de-tramite.git
    dockerfilePath: ./phpmyadmin.Dockerfile
    envVars:
      - key: PMA_HOST
        value: tramite-db.onrender.com
      - key: PMA_PORT
        value: 3306